project:
  type: website
  output-dir: ../docs-quarto
website:
  title: "Virtual Biophysical Lab"
  navbar:
    left:
      - text: "Overview"
        href: index.qmd
      - text: "ToolsRTM"
        href: toolsrtm.qmd
      - text: "SCOPEinR"
        href: scopeinr.qmd
      - text: "Modules"
        href: modules.qmd
      - text: "Use cases"
        href: use-cases.qmd
      - text: "Getting started"
        href: getting-started.qmd
      - text: "Status"
        href: status.qmd
      - text: "Conferences"
        href: conferences.qmd
      - text: "Tutorials"
        href: tutorials.qmd


format:
  html:
    theme: default         # usamos tema base, pero lo sobreescribimos con CSS
    css: styles.css
    toc: false
    page-layout: full
    eval: false
    code-copy: true     # shows the "Copy" button
    code-overflow: wrap
